'use strict';

// Default card content. Everything here is editable from the admin panel.
// The shape of this object is also the schema: unknown keys sent by the
// admin panel are dropped, and missing keys fall back to these values.

const config = {
  couple: {
    groomShort: 'Adam',
    brideShort: 'Hawa',
    groomFull: 'Muhammad Adam bin Ahmad',
    brideFull: 'Nur Hawa binti Ismail',
    order: 'groom-first',
  },
  cover: {
    topText: 'Walimatul Urus',
    subText: 'Jemputan Perkahwinan',
    buttonText: 'Buka',
  },
  hero: {
    bismillah: 'بِسْمِ ٱللَّٰهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ',
    title: 'Walimatul Urus',
    tagline: 'Dua jiwa, satu ikatan, kerana Allah',
  },
  invite: {
    greeting: 'Assalamualaikum Warahmatullahi Wabarakatuh',
    hosts: 'Ahmad bin Abdullah\n&\nSiti binti Hassan',
    text: "Dengan penuh kesyukuran ke hadrat Ilahi, kami menjemput\nDato' / Datin / Tuan / Puan / Encik / Cik\nseisi keluarga ke majlis perkahwinan anakanda kami",
    closing: 'Semoga kehadiran dan doa restu tuan/puan memberkati majlis ini.',
    verse: '“Dan di antara tanda-tanda kekuasaan-Nya ialah Dia menciptakan untukmu pasangan dari jenismu sendiri, supaya kamu hidup tenteram bersamanya.”\n— Surah Ar-Rum, 30:21',
  },
  event: {
    title: 'Butiran Majlis',
    date: '2026-12-12',
    startTime: '11:00',
    endTime: '16:00',
    dateText: '',
    timeText: '11:00 pagi – 4:00 petang',
    hijriDate: '2 Rejab 1448H',
    venueName: 'Dewan Seri Angkasa',
    address: 'Jalan Bukit Bintang, 55100 Kuala Lumpur',
    googleMapsUrl: '',
    wazeUrl: '',
    showCountdown: true,
    countdownTitle: 'Menghitung Hari',
    itineraryTitle: 'Aturcara Majlis',
    itinerary: [
      { time: '11:00 pagi', label: 'Ketibaan tetamu & jamuan makan', timeEn: '11:00 am', labelEn: 'Guests arrive & lunch is served' },
      { time: '12:30 tengah hari', label: 'Ketibaan pengantin', timeEn: '12:30 pm', labelEn: 'Arrival of the bride and groom' },
      { time: '1:00 petang', label: 'Makan beradab & potong kek', timeEn: '1:00 pm', labelEn: 'Bridal table & cake cutting' },
      { time: '4:00 petang', label: 'Majlis bersurai', timeEn: '4:00 pm', labelEn: 'Event ends' },
    ],
  },
  attire: {
    enabled: true,
    title: 'Tema Busana',
    description: 'Tetamu dijemput hadir dengan busana mengikut tema warna majlis.',
    colors: [
      { name: 'Sage', hex: '#9caf88', nameEn: 'Sage' },
      { name: 'Krim', hex: '#efe6d2', nameEn: 'Cream' },
      { name: 'Emas Lembut', hex: '#c9a24b', nameEn: 'Soft Gold' },
    ],
    image: '',
    notes: 'Lelaki: Baju Melayu / Batik\nWanita: Baju Kurung / Kebaya, menutup aurat',
  },
  rsvp: {
    enabled: true,
    title: 'RSVP',
    description: 'Sila maklumkan kehadiran anda sebelum 30 November 2026.',
    deadline: '2026-11-30',
    maxPax: 5,
    successTitle: 'Terima kasih!',
    successText: 'Maklum balas anda telah direkodkan. Simpan tarikh majlis dan jumpa di sana.',
    closedText: 'RSVP telah ditutup. Sila hubungi keluarga untuk sebarang pertanyaan.',
  },
  wishes: {
    enabled: true,
    title: 'Ucapan & Doa',
    description: 'Titipan doa daripada keluarga dan sahabat handai.',
    emptyText: 'Jadilah yang pertama menitipkan ucapan melalui borang RSVP.',
    speed: 30,
  },
  moneyGift: {
    enabled: true,
    title: 'Salam Kaut',
    description: 'Doa restu anda sudah cukup bermakna. Namun sekiranya ingin menghulur salam kaut, boleh salurkan melalui akaun di bawah.',
    bankName: 'Maybank',
    accountName: 'Muhammad Adam bin Ahmad',
    accountNumber: '1234 5678 9012',
    qrImage: '',
    qrCaption: 'Imbas kod QR DuitNow',
  },
  registry: {
    enabled: true,
    title: 'Hadiah',
    description: 'Sekiranya ingin menghadiahkan sesuatu, pilih dan tempah daripada senarai di bawah supaya tiada hadiah yang bertindih.',
    emptyText: 'Senarai hadiah akan dikemas kini tidak lama lagi.',
    autoSeconds: 6,
  },
  thanks: {
    enabled: true,
    title: 'Terima Kasih',
    text: 'Kehadiran serta doa restu tuan/puan amat kami hargai. Semoga Allah membalas dengan sebaik-baik ganjaran.',
    signature: 'Ikhlas daripada kedua-dua keluarga',
    hashtag: '#AdamHawa2026',
    buttonText: 'Hubungi Keluarga',
    contactsTitle: 'Hubungi Keluarga',
    contacts: [
      { name: 'Ahmad', role: 'Bapa pengantin lelaki', phone: '012-345 6789', roleEn: "Groom's father" },
      { name: 'Siti', role: 'Ibu pengantin lelaki', phone: '013-456 7890', roleEn: "Groom's mother" },
      { name: 'Ismail', role: 'Bapa pengantin perempuan', phone: '019-876 5432', roleEn: "Bride's father" },
    ],
  },
  // Link preview shown by WhatsApp, Telegram, Facebook and others when the
  // card's link is shared. An empty title is written from the couple's names.
  share: {
    title: '',
    description: 'Dengan segala hormatnya, anda dijemput ke majlis perkahwinan kami. Buka kad untuk butiran majlis dan RSVP.',
    image: '',
  },
  footer: {
    enabled: true,
    text: 'Rekaan oleh Kad Kahwin',
    link: '',
  },
  language: {
    enabled: true,
    default: 'ms',
  },
  // English wording. Only text that differs between languages lives here; an
  // empty value falls back to the Bahasa Malaysia text above (the date and
  // time are written out automatically instead). List items carry their
  // English text in "...En" fields.
  en: {
    cover: {
      topText: 'The Wedding Of',
      subText: 'Wedding Invitation',
      buttonText: 'Open',
    },
    hero: {
      title: 'The Wedding Of',
      tagline: 'Two souls, one bond, for the sake of Allah',
    },
    invite: {
      greeting: 'Assalamualaikum Warahmatullahi Wabarakatuh',
      text: "With gratitude to the Almighty, we cordially invite\nDato' / Datin / Mr / Mrs / Ms\nand family to the wedding reception of our beloved children",
      closing: 'Your presence and prayers will be a blessing to this occasion.',
      verse: '“And of His signs is that He created for you spouses from among yourselves, that you may find tranquillity in them.”\n— Surah Ar-Rum, 30:21',
    },
    event: {
      title: 'Event Details',
      dateText: '',
      timeText: '',
      hijriDate: '',
      venueName: '',
      address: '',
      countdownTitle: 'Counting Down',
      itineraryTitle: 'Programme',
    },
    attire: {
      title: 'Dress Code',
      description: 'Guests are invited to dress in the colours of the wedding theme.',
      notes: 'Men: Baju Melayu / Batik\nWomen: Baju Kurung / Kebaya, modest attire',
    },
    rsvp: {
      title: 'RSVP',
      description: 'Kindly let us know whether you will be attending.',
      successTitle: 'Thank you!',
      successText: 'Your response has been recorded. Save the date and see you there.',
      closedText: 'RSVP is now closed. Please contact the family for any enquiries.',
    },
    wishes: {
      title: 'Wishes & Prayers',
      description: 'Kind words from family and friends.',
      emptyText: 'Be the first to leave a wish through the RSVP form.',
    },
    moneyGift: {
      title: 'Salam Kaut',
      description: 'Your prayers and blessings mean the most to us. Should you wish to give a monetary gift, you may use the account below.',
      qrCaption: 'Scan the DuitNow QR code',
    },
    registry: {
      title: 'Gifts',
      description: 'If you would like to give a gift, please choose and reserve one from the list below so that no gift is duplicated.',
      emptyText: 'The gift list will be updated soon.',
    },
    thanks: {
      title: 'Thank You',
      text: 'We truly appreciate your presence and prayers. May Allah reward you with the best of rewards.',
      signature: 'With love from both families',
      buttonText: 'Contact Family',
      contactsTitle: 'Contact Family',
    },
    share: {
      title: '',
      description: 'You are cordially invited to our wedding. Open the card for the event details and to RSVP.',
    },
    footer: {
      text: 'Design by Kad Kahwin',
    },
    labels: {
      days: 'Days',
      hours: 'Hours',
      minutes: 'Minutes',
      seconds: 'Seconds',
      name: 'Name',
      phone: 'Phone Number',
      attendance: 'Attendance',
      attending: 'Attending',
      notAttending: 'Not Attending',
      pax: 'Number of guests',
      wish: 'Wish (optional)',
      submit: 'Send RSVP',
      editRsvp: 'Update RSVP',
      saveCalendar: 'Save to calendar',
      googleCalendar: 'Google Calendar',
      icsCalendar: 'Apple / Outlook',
      directions: 'Directions to the venue',
      googleMaps: 'Google Maps',
      waze: 'Waze',
      bank: 'Bank',
      accountName: 'Account name',
      accountNumber: 'Account number',
      copy: 'Copy account number',
      copied: 'Copied!',
      reserve: 'Reserve this gift',
      reserved: 'Already reserved',
      reservedByYou: 'Reserved by you',
      reserveTitle: 'Reserve a Gift',
      reserveNote: 'Fill in your details to reserve this gift.',
      confirmReserve: 'Confirm reservation',
      reserveSuccess: 'Gift reserved. Thank you!',
      giftTaken: 'Sorry, this gift has just been reserved by another guest.',
      viewItem: 'View item',
      call: 'Call',
      whatsapp: 'WhatsApp',
      close: 'Close',
      navContact: 'Contact',
      navLocation: 'Location',
      navRsvp: 'RSVP',
      navGift: 'Gifts',
      navMusic: 'Music',
      errRequired: 'Please enter your name and a valid phone number.',
      errGeneric: 'Sorry, something went wrong. Please try again shortly.',
    },
  },
  music: {
    url: '',
    autoplay: true,
  },
  labels: {
    days: 'Hari',
    hours: 'Jam',
    minutes: 'Minit',
    seconds: 'Saat',
    name: 'Nama',
    phone: 'No. Telefon',
    attendance: 'Kehadiran',
    attending: 'Hadir',
    notAttending: 'Tidak Hadir',
    pax: 'Bilangan kehadiran',
    wish: 'Ucapan (pilihan)',
    submit: 'Hantar RSVP',
    editRsvp: 'Kemas kini RSVP',
    saveCalendar: 'Simpan ke kalendar',
    googleCalendar: 'Google Calendar',
    icsCalendar: 'Apple / Outlook',
    directions: 'Arah ke lokasi',
    googleMaps: 'Google Maps',
    waze: 'Waze',
    bank: 'Bank',
    accountName: 'Nama akaun',
    accountNumber: 'No. akaun',
    copy: 'Salin no. akaun',
    copied: 'Disalin!',
    reserve: 'Tempah hadiah ini',
    reserved: 'Telah ditempah',
    reservedByYou: 'Ditempah oleh anda',
    reserveTitle: 'Tempah Hadiah',
    reserveNote: 'Isikan butiran anda untuk menempah hadiah ini.',
    confirmReserve: 'Sahkan tempahan',
    reserveSuccess: 'Hadiah berjaya ditempah. Terima kasih!',
    giftTaken: 'Maaf, hadiah ini baru sahaja ditempah oleh tetamu lain.',
    viewItem: 'Lihat item',
    call: 'Telefon',
    whatsapp: 'WhatsApp',
    close: 'Tutup',
    navContact: 'Hubungi',
    navLocation: 'Lokasi',
    navRsvp: 'RSVP',
    navGift: 'Hadiah',
    navMusic: 'Muzik',
    errRequired: 'Sila isi nama dan nombor telefon yang sah.',
    errGeneric: 'Maaf, berlaku ralat. Sila cuba sebentar lagi.',
  },
  design: {
    theme: 'emerald',
    custom: {
      enabled: false,
      primary: '#0f4c3a',
      accent: '#c9a24b',
      bg: '#f7f3e9',
      surface: '#fffdf7',
      text: '#23302b',
    },
    fontHeading: 'Cormorant Garamond',
    fontScript: 'Great Vibes',
    fontBody: 'Poppins',
    bodyWeight: 'medium',
    pattern: 'islamic-star',
    patternOpacity: 0.1,
    effect: 'petals',
    scrollAnimation: 'fade-up',
    opening: 'doors',
    coverDesign: 'classic',
    coverTone: 'primary',
    coverImage: '',
    sealStyle: 'gold',
    heroShape: 'arch',
    heroFrame: 'floral-corners',
    frameColor: '#e8a9b6',
    heroFrameImage: '',
    heroTextColor: 'primary',
    nameHighlight: 'frame',
    songket: 'none',
    songketPlace: 'both',
    // Text size per element, in percent. Keys match FONT_SIZES in public/js/shared.js.
    fontSizes: Object.fromEntries(
      [
        'all',
        'coverTop', 'coverNames', 'coverDate', 'coverButton', 'coverSub',
        'bismillah', 'heroTitle', 'heroNames', 'heroDate', 'heroVenue', 'tagline',
        'greeting', 'hosts', 'inviteText', 'coupleFull', 'ampersand', 'verse',
        'sectionTitle', 'subTitle', 'description', 'smallNote', 'miniTitle', 'button', 'textLink', 'toast',
        'eventMain', 'eventTime', 'countdownNumber', 'countdownLabel', 'programmeTime', 'programmeText',
        'swatchName', 'attireNotes',
        'formLabel', 'formChoice', 'formInput',
        'wishText', 'wishName', 'emptyText',
        'bankLabel', 'bankValue', 'accountNumber',
        'giftName', 'giftText', 'giftBadge',
        'thanksNames', 'hashtag', 'contactName', 'contactDetail', 'credit',
        'dock',
      ].map((key) => [key, 100])
    ),
  },
};

// Item shapes for the list fields above (lists may be emptied by the admin).
const listItems = {
  'event.itinerary': { time: '', label: '', timeEn: '', labelEn: '' },
  'attire.colors': { name: '', hex: '', nameEn: '' },
  'thanks.contacts': { name: '', role: '', phone: '', roleEn: '' },
};

const gift = { name: '', description: '', price: '', link: '', image: '', nameEn: '', descriptionEn: '' };

const sampleGifts = [
  { name: 'Set Pinggan Mangkuk', description: 'Set 16 keping, warna putih atau krim', price: 'RM 180', link: '', image: '', nameEn: 'Dinnerware Set', descriptionEn: '16-piece set, white or cream' },
  { name: 'Air Fryer', description: 'Kapasiti 5L ke atas', price: 'RM 250', link: '', image: '', nameEn: 'Air Fryer', descriptionEn: '5L capacity or larger' },
  { name: 'Set Cadar Queen', description: 'Kain kapas, warna lembut', price: 'RM 150', link: '', image: '', nameEn: 'Queen Bedsheet Set', descriptionEn: 'Cotton, soft colours' },
];

module.exports = { config, listItems, gift, sampleGifts };
